### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by aalap** [iancanderson/ingreedy-js#2]
Even after doing a npm install 

I still get , on doing this
var ingreedy = require('ingreedy-js');

Error: Cannot find module 'ingreedy-js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/asharma4/my-sails-app/api/services/scrape.js:6:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/local/lib/node_modules/sails/node_modules/include-all/index.js:129:29
    at Array.forEach (native)

**Comment by bhoomika911** [comment]
I have same problem.

Can any one help?

**Comment by shadowtime2000** [comment]
I copied the parser.js file into my project folder and wrote `module.exports = Ingreedy`. Then, I can import it with:
`var Ingreedy = require("./parser.js");`

**Comment by shadowtime2000** [comment]
It seems like the problem exists because the parser file did not export the parser and the package.json file didn't have the main field specified as the parser file.
